openapi: 3.0.0
info:
  title: "Cinema-app"
  description: "cinema-app for course-work"
  version: 0.0.1
servers:
  - url: "/api"
paths:
  /films:
    get:
      operationId: "controllers.FilmsController.read_all"
      tags:
        - "films"
      summary: "Read the list of films"
      responses:
        "200":
          description: "Success"
  /filmsessions:
    get:
      operationId: "controllers.FilmSessionsController.read_all"
      tags:
        - "filmSessions"
      summary: "Read the list of sessions"
      responses:
        "200":
          description: "Success"
  /orders:
    get:
      operationId: "controllers.OrdersController.read_all"
      tags:
        - "orders"
      summary: "Read the list of orders"
      responses:
        "200":
          description: "Success"
